# Generated by BoostInstall.cmake for boost_unordered-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.80.0 EXACT)
find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_container_hash 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_move 1.80.0 EXACT)
find_dependency(boost_mp11 1.80.0 EXACT)
find_dependency(boost_predef 1.80.0 EXACT)
find_dependency(boost_preprocessor 1.80.0 EXACT)
find_dependency(boost_throw_exception 1.80.0 EXACT)
find_dependency(boost_tuple 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_unordered-targets.cmake")
