# Generated by BoostInstall.cmake for boost_lockfree-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_align 1.80.0 EXACT)
find_dependency(boost_array 1.80.0 EXACT)
find_dependency(boost_assert 1.80.0 EXACT)
find_dependency(boost_atomic 1.80.0 EXACT)
find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_integer 1.80.0 EXACT)
find_dependency(boost_iterator 1.80.0 EXACT)
find_dependency(boost_mpl 1.80.0 EXACT)
find_dependency(boost_parameter 1.80.0 EXACT)
find_dependency(boost_predef 1.80.0 EXACT)
find_dependency(boost_static_assert 1.80.0 EXACT)
find_dependency(boost_tuple 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)
find_dependency(boost_utility 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_lockfree-targets.cmake")
