# Copyright 2019 VMware, all rights reserved.
# This software is released under MIT license.
# The full license information can be found in LICENSE in the root directory of this project.

# Connect to existing docker default network for local development
version: '3'

services:

  supply-chain:
    networks:
      - default

networks:
  default:
    external:
      name: docker_default
