# Generated by BoostInstall.cmake for boost_function_types-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_detail 1.80.0 EXACT)
find_dependency(boost_mpl 1.80.0 EXACT)
find_dependency(boost_preprocessor 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_function_types-targets.cmake")
