apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: concord-pvc-{{ .Values.global.blockchainId }}-replica-3
spec:
  storageClassName: "{{ .Values.storageClassNames.replica.replica3 | default .Values.global.storageClassName}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.resources.replica.storageRequest | default .Values.resources.replica.defaultStorageRequest }}"