# Generated by BoostInstall.cmake for boost_variant-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.80.0 EXACT)
find_dependency(boost_bind 1.80.0 EXACT)
find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_container_hash 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_detail 1.80.0 EXACT)
find_dependency(boost_integer 1.80.0 EXACT)
find_dependency(boost_move 1.80.0 EXACT)
find_dependency(boost_mpl 1.80.0 EXACT)
find_dependency(boost_preprocessor 1.80.0 EXACT)
find_dependency(boost_static_assert 1.80.0 EXACT)
find_dependency(boost_throw_exception 1.80.0 EXACT)
find_dependency(boost_type_index 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)
find_dependency(boost_utility 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_variant-targets.cmake")
