
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-22T09:44:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "13f87d0c9feeb2b58d1d1feeff8df708819ec685",
 "version": "21.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
