# Generated by BoostInstall.cmake for boost_iterator-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.80.0 EXACT)
find_dependency(boost_concept_check 1.80.0 EXACT)
find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_conversion 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_detail 1.80.0 EXACT)
find_dependency(boost_function_types 1.80.0 EXACT)
find_dependency(boost_fusion 1.80.0 EXACT)
find_dependency(boost_mpl 1.80.0 EXACT)
find_dependency(boost_optional 1.80.0 EXACT)
find_dependency(boost_smart_ptr 1.80.0 EXACT)
find_dependency(boost_static_assert 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)
find_dependency(boost_utility 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_iterator-targets.cmake")
