# Copyright 2019 VMware, all rights reserved.
# This software is released under MIT license.
# The full license information can be found in LICENSE in the root directory of this project.


version: '3'
services:
  supply-chain:
    image: "mrharrison/supply-chain:latest"
    # build:
    #   context: .
    command: "npm run start:vmware"
    ports:
      - 4200:4200
    volumes:
      - ./contracts:/app/contracts
      - ./src/app/core/blockchain/:/app/src/app/core/blockchain/
      - ./migrations:/app/migrations
      - ./build:/app/build
      - ./truffle-config.js:/app/truffle-config.js
    environment:
      # Example
      # - BC_URL=http://localhost/blockchains/local/api/concord/eth
      - BC_URL=<change-me>
# Connect to existing docker default network for local development
    # networks:
    #   - default

# networks:
#   default:
#     external:
#       name: docker_default
