# Generated by BoostInstall.cmake for boost_asio-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_align 1.80.0 EXACT)
find_dependency(boost_array 1.80.0 EXACT)
find_dependency(boost_assert 1.80.0 EXACT)
find_dependency(boost_bind 1.80.0 EXACT)
find_dependency(boost_chrono 1.80.0 EXACT)
find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_coroutine 1.80.0 EXACT)
find_dependency(boost_date_time 1.80.0 EXACT)
find_dependency(boost_function 1.80.0 EXACT)
find_dependency(boost_regex 1.80.0 EXACT)
find_dependency(boost_smart_ptr 1.80.0 EXACT)
find_dependency(boost_system 1.80.0 EXACT)
find_dependency(boost_throw_exception 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)
find_dependency(boost_utility 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_asio-targets.cmake")
