# Generated by BoostInstall.cmake for boost_foreach-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_iterator 1.80.0 EXACT)
find_dependency(boost_mpl 1.80.0 EXACT)
find_dependency(boost_range 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_foreach-targets.cmake")
