# Generated by BoostInstall.cmake for boost_winapi-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_predef 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_winapi-targets.cmake")
