# Generated by BoostInstall.cmake for boost_locale-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.80.0 EXACT)
find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_function 1.80.0 EXACT)
find_dependency(boost_iterator 1.80.0 EXACT)
find_dependency(boost_smart_ptr 1.80.0 EXACT)
find_dependency(boost_static_assert 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)
find_dependency(boost_thread 1.80.0 EXACT)
find_dependency(boost_unordered 1.80.0 EXACT)
find_dependency(boost_predef 1.80.0 EXACT)
find_dependency(Iconv)

include("${CMAKE_CURRENT_LIST_DIR}/boost_locale-targets.cmake")
