# Generated by BoostInstall.cmake for boost_date_time-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_algorithm 1.80.0 EXACT)
find_dependency(boost_assert 1.80.0 EXACT)
find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_io 1.80.0 EXACT)
find_dependency(boost_lexical_cast 1.80.0 EXACT)
find_dependency(boost_numeric_conversion 1.80.0 EXACT)
find_dependency(boost_range 1.80.0 EXACT)
find_dependency(boost_smart_ptr 1.80.0 EXACT)
find_dependency(boost_static_assert 1.80.0 EXACT)
find_dependency(boost_throw_exception 1.80.0 EXACT)
find_dependency(boost_tokenizer 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)
find_dependency(boost_utility 1.80.0 EXACT)
find_dependency(boost_winapi 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_date_time-targets.cmake")
