# Generated by BoostInstall.cmake for boost_program_options-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_any 1.80.0 EXACT)
find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_detail 1.80.0 EXACT)
find_dependency(boost_function 1.80.0 EXACT)
find_dependency(boost_iterator 1.80.0 EXACT)
find_dependency(boost_lexical_cast 1.80.0 EXACT)
find_dependency(boost_smart_ptr 1.80.0 EXACT)
find_dependency(boost_static_assert 1.80.0 EXACT)
find_dependency(boost_throw_exception 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)
find_dependency(boost_bind 1.80.0 EXACT)
find_dependency(boost_tokenizer 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_program_options-targets.cmake")
