apiVersion: v1
kind: Secret
metadata:
  name: vmbc-secret-client-0-ethrpc
data:
  # cert private keys
  {{ range $path, $_ := .Files.Glob "client-0/config/ethrpc/*/*.pem" }}
  {{- $path | replace "/" "-" | indent 2 }}: {{ $.Files.Get $path | b64enc }}
  {{ end }}