# Generated by BoostInstall.cmake for boost_algorithm-1.80.0

include(CMakeFindDependencyMacro)

find_dependency(boost_array 1.80.0 EXACT)
find_dependency(boost_assert 1.80.0 EXACT)
find_dependency(boost_bind 1.80.0 EXACT)
find_dependency(boost_concept_check 1.80.0 EXACT)
find_dependency(boost_config 1.80.0 EXACT)
find_dependency(boost_core 1.80.0 EXACT)
find_dependency(boost_exception 1.80.0 EXACT)
find_dependency(boost_function 1.80.0 EXACT)
find_dependency(boost_iterator 1.80.0 EXACT)
find_dependency(boost_mpl 1.80.0 EXACT)
find_dependency(boost_range 1.80.0 EXACT)
find_dependency(boost_regex 1.80.0 EXACT)
find_dependency(boost_static_assert 1.80.0 EXACT)
find_dependency(boost_throw_exception 1.80.0 EXACT)
find_dependency(boost_tuple 1.80.0 EXACT)
find_dependency(boost_type_traits 1.80.0 EXACT)
find_dependency(boost_unordered 1.80.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_algorithm-targets.cmake")
